---
version: "3"
services:
  android-retools:
    build:
      context: .
      dockerfile: Dockerfile.re
      args:
        - SSH_PASSWORD=mypass
        - VNC_PASSWORD=mypass
    image: cryptax/android-re:2024.02
    container_name: android-retools
    ports:
      - "6022:22"
      - "6900:5900"
      - "6800:8000"
    volumes:
      - /tmp/retools:/workshop
